### ISSUE TITLE
Having trouble with Data types

### ISSUE THREAD

**Issue by seanpatcleary** [thejonaslab/rassp-public#1]
Hello,

I recently was able to go through the process of getting the rassp package installed, and everything seems to work fine except for one small issue.  If I try to run the sample data that you provide, I run into the following issue

Traceback (most recent call last):
  File ".\rassp\run_rassp.py", line 413, in <module>
    run_predictions()
  File "C:\Users\sean\anaconda3\envs\raasp\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\sean\anaconda3\envs\raasp\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\sean\anaconda3\envs\raasp\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\sean\anaconda3\envs\raasp\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File ".\rassp\run_rassp.py", line 409, in run_predictions
    num_data_workers,
  File ".\rassp\run_rassp.py", line 335, in run_on_file
    all_results, pred_metadata = predictor.predict(mols, model_name=model_name)
  File ".\rassp\run_rassp.py", line 247, in predict
    benchmark_dataloader=False,
  File "c:\users\sean\desktop\rassp-public-main\rassp\netutil.py", line 538, in pred
    for batch_i, features_batch_tensor in enumerate(batch_iterator):
  File "C:\Users\sean\anaconda3\envs\raasp\lib\site-packages\tqdm\std.py", line 1167, in __iter__
    for obj in iterable:
  File "C:\Users\sean\anaconda3\envs\raasp\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\sean\anaconda3\envs\raasp\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "C:\Users\sean\anaconda3\envs\raasp\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "C:\Users\sean\anaconda3\envs\raasp\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\sean\anaconda3\envs\raasp\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\sean\anaconda3\envs\raasp\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\sean\anaconda3\envs\raasp\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\users\sean\desktop\rassp-public-main\rassp\dataset\__init__.py", line 123, in __getitem__
    features_dict = self.featurizer(mol)
  File "c:\users\sean\desktop\rassp-public-main\rassp\featurize\featurize.py", line 156, in __call__
    vertsubsets = vert_subset_generator(mol)
  File "c:\users\sean\desktop\rassp-public-main\rassp\featurize\featurize.py", line 204, in run
    return msutil.vertsubsetgen.BreakAndRearrangeFast(**config)(mol)
  File "c:\users\sean\desktop\rassp-public-main\rassp\msutil\vertsubsetgen.py", line 495, in __call__
    explicit_h)
  File "rassp\msutil\vertsubsetgen_fast.pyx", line 325, in rassp.vertsubsetgen_fast.subsets_from_edge_removals
    np.int64_t[:, :] valid_h_donations,
ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'long'

For clarity, I'm running on a windows machine, which, when researching this error, I suspect may be the issue.  Do you have a simple workaround to fix this issue?

Edit.  Realized I should probably show you the command I'm running from conda.  The command I ran was:

python .\rassp\run_rassp.py sample_data\in.txt sample_data\out.txt --file-type inchi --output-file-type txt --model-name SubsetNet

**Comment by richardzhu** [comment]
That's an interesting error. I did some quick searching and found [this issue](https://github.com/hlin117/mdlp-discretization/issues/21), which suggests some platform-dependent type casting issue.

One possible answer in `rassp/msutil/vertsubsetgen.py:L472`:
```
        valid_h_donations = np.array(list(itertools.product(heavy_atom_inds_with_hs, heavy_atom_inds)), np.int64)
        if len(valid_h_donations) == 0:
            # array needs to have 2-dims and we explicitly do_rearrange
            # later, so this needs to be a rearrange no-op
            # we check for -1, -1 in `do_rearrangements_lut_bits`
            valid_h_donations = np.array([[-1, -1]], dtype=np.int64)
```
I added the explicit casting of `dtype=np.int64` to the `np.array` calls that form `valid_h_donations`.

Does that fix the issue?

If you did `pip install -e .` for `rassp` then the fix should propagate without any changes, otherwise you might want to uninstall and reinstall `rassp`.

There are few other points where types are mis-specified or not exactly specified, but unfortunately I don't have a Windows machine to test with. I would suggest trying [WSL](https://learn.microsoft.com/en-us/windows/wsl/about) as it's closer to the Mac/Unix systems we develop with.

**Comment by seanpatcleary** [comment]
Sounds good.  

I actually built the conda env in wsl and it worked well, but I'm hoping to pass this on to cowrokers less comfortable with Linux/ more comfortable with windows.  If you'd like, I can spend some time and try to get you a pull request for windows users if I'm able to get it working.  The initial fixes caused an overflow issue btw.  

On a positive side note, I gotta say, with what I've done thus far with Linux, this program is awesome. Thanks for sharing!

**Comment by Evan-Allgair** [comment]
Hello,
I am looking to set up RASSP for coworkers, for the exact same reason that they are not going to be able to get things to work in Linux. I ended up getting the same issue on windows, came up with that exact type cast fix myself, and also ended in an overflow error. Have you been able to get this to work on a windows based system? If not, I will try it on WSL, but would really love to not forfeit my laptop for the use of the program, as it seems to be VERY powerful and our first choice.

**Comment by csu-jialong** [comment]
Hello, I'm running the following command on my Windows system and it gives me an error, I've changed the path and still can't find meta.

(rassp) d:\EdgeDownloads\rassp-public\rassp>python run_rassp.py "sample_data/in.txt" "sample_data/out.txt" --file-type inchi --output-file-type txt --model-name "FormulaNet" --no-gpu
Loading mols from provided file sample_data/in.txt
Loaded 50 mols
Initializing Predictor
Running RASSP forward model
2024-09-08 09:53:02,319 - __main__ - INFO - Loading model FormulaNet
Traceback (most recent call last):
  File "run_rassp.py", line 449, in <module>
    run_predictions()
  File "D:\Anaconda\envs\rassp\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\Anaconda\envs\rassp\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\Anaconda\envs\rassp\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Anaconda\envs\rassp\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "run_rassp.py", line 442, in run_predictions
    num_data_workers,
  File "run_rassp.py", line 368, in run_on_file
    all_results, pred_metadata = predictor.predict(mols, model_name=model_name)
  File "run_rassp.py", line 254, in predict
    predictor, meta = Predictor.load_model(model_name, use_gpu=self.use_gpu)
  File "run_rassp.py", line 219, in load_model
    assert os.path.exists(meta_path), f'meta not found at {meta_path}'
AssertionError: meta not found at D:\EdgeDownloads\rassp-public\rassp\models\formulanet_best_candidate_pcsim_pretrain.nist-fromscratch-3x9x128.35790555.meta

I print the MODELS dict

{'FormulaNet': {'checkpoint': 'D:\\EdgeDownloads\\rassp-public\\rassp\\models\\formulanet_best_candidate_pcsim_pretrain.nist-fromscratch-3x9x128.35790555.00000740.model', 'meta': 'D:\\EdgeDownloads\\rassp-public\\rassp\\models\\formulanet_best_candidate_pcsim_pretrain.nist-fromscratch-3x9x128.35790555.meta', 'override_constraints': {'n_atom': 48, 'n_formula': 32768, 'n_subset': 49152}}, 'SubsetNet': {'checkpoint': 'D:\\EdgeDownloads\\rassp-public\\rassp\\models\\subsetnet_best_candidate_nist_fromscratch.nist-fromscratch-test01-old-1x2048.36688199.00001000.model', 'meta': 
'D:\\EdgeDownloads\\rassp-public\\rassp\\models\\subsetnet_best_candidate_nist_fromscratch.nist-fromscratch-test01-old-1x2048.36688199.meta', 'override_constraints': {'n_atom': 64, 'n_formula': 32768, 'n_subset': 49152}}}
